bib/config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  #delete 'logout', to: 'sessions#destroy', as: 'logout'
  delete '/logout', to: 'sessions#destroy'




  # Routes pour Adhérents
  resources :adherents

  # Routes pour Documents
  resources :documents

  # Routes pour Matériels
  resources :materiels

  # Routes pour Emprunts
  resources :emprunts

  # Si vous avez une page d'accueil ou un contrôleur spécifique pour gérer la racine de l'application
  root 'home#index'  # Assurez-vous d'avoir un HomeController avec une action index
end

bib/app/models/emprunt.rb
class Emprunt < ApplicationRecord
  # belongs_to :adherent
  # belongs_to :item, polymorphic: true

  # validate :check_max_emprunts
  # validates :item_type, inclusion: { in: ['livre', 'Materiel', ''], message: "%{value} is not a valid item type" }

  # private

  # def check_max_emprunts
  #   if item_type == 'Document' && adherent.emprunts.where(item_type: 'Document').count >= 5
  #     errors.add(:base, "Un adhérent ne peut emprunter plus de cinq documents.")
  #   elsif item_type == 'Materiel' && adherent.emprunts.where(item_type: 'Materiel').count >= 1
  #     errors.add(:base, "Un adhérent ne peut emprunter qu'un seul matériel.")
  #   end
  # end

  belongs_to :item, optional: true
  belongs_to :adherent
  belongs_to :item, polymorphic: true

  validate :check_max_emprunts
  after_create :mark_item_as_unavailable




  private
  def check_max_emprunts
    if item_type == 'Document' && adherent.document_count.to_i >= 5
      errors.add(:base, "Un adhérent ne peut emprunter plus de cinq livres.")
    elsif item_type == 'Materiel' && adherent.materiel_count.to_i >= 1
      errors.add(:base, "Un adhérent ne peut emprunter qu'un seul ordinateur portable.")
    end
  end
  def mark_item_as_unavailable
    item.update(disponible: false)
  end

end

bib/app/controllers/emprunts_controller.rb
class EmpruntsController < ApplicationController
  before_action :authenticate_admin

  before_action :set_emprunt, only: [:show, :edit, :update, :destroy]
  def authenticate_admin
    unless current_admin
      redirect_to login_path, alert: "Please sign in first."
    end
  end

  def index
    @emprunts = Emprunt.includes(:adherent, :item).all
  end

  def show
  end

  def new
    @emprunt = Emprunt.new
    @documents = Document.all
    @materiels = Materiel.all
  end

  def edit
  end

  # def create
  #   @emprunt = Emprunt.new(emprunt_params)
  #   if @emprunt.save
  #     redirect_to @emprunt, notice: 'Emprunt was successfully created.'
  #   else
  #     render :new
  #   end
  # end
  def create
    @emprunt = Emprunt.new(emprunt_params)
    if @emprunt.save
      redirect_to @emprunt, notice: 'Emprunt was successfully created.'
    else
      render :new
    end
  end

  def update
    if @emprunt.update(emprunt_params)
      redirect_to @emprunt, notice: 'Emprunt was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @emprunt.destroy
    redirect_to emprunts_url, notice: 'Emprunt was successfully destroyed.'
  end

  private

  def set_emprunt
    @emprunt = Emprunt.find(params[:id])
  end

  def emprunt_params
    params.require(:emprunt).permit(:adherent_id, :item_id, :item_type)
  end
end

bib/app/helpers/emprunts_helper.rb
module EmpruntsHelper
end

bib/app/views/emprunts/_document_fields.html.erb
<div class="field">
  <%= form.label :document_id %>
  <%= form.collection_select :document_id, Document.all, :id, :titre %>
</div>

bib/app/views/emprunts/_form.html.erb
<div class="container">
  <div class="text-center">
    <%= form_with(model: @emprunt) do |form| %>
      <% if @emprunt.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@emprunt.errors.count, "erreur") %> empêche(nt) la sauvegarde de cet emprunt :</h2>
          <ul>
            <% @emprunt.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :adherent_id %>
        <%= form.collection_select :adherent_id, Adherent.all, :id, :full_name, {}, { class: "form-control" } %>
      </div>

      <div class="form-group">
        <%= form.label :item_type %>
        <%= form.select :item_type, options_for_select(['', 'Document', 'Materiel']), {}, { id: 'item_type_select', class: "form-control" } %>
      </div>

      <div class="form-group" id="document_field" style="display: none;">
        <%= form.label :item_id %>
        <%= form.collection_select :item_id, Document.where(disponible: true), :id, :display_name, {}, { id: 'document_id_select', class: "form-control" } %>
      </div>

      <div class="form-group" id="materiel_field" style="display: none;">
        <%= form.label :item_id %>
        <%= form.collection_select :item_id, Materiel.where(disponible: true), :id, :display_name, {}, { id: 'materiel_id_select', class: "form-control" } %>
      </div>

      <div class="form-group">
        <%= form.submit 'Enregistrer', class: "btn btn-primary" %>
      </div>

      <script>
        document.addEventListener("DOMContentLoaded", function() {
          const itemTypeIdSelect = document.getElementById('item_type_select');
          const documentField = document.getElementById('document_field');
          const materielField = document.getElementById('materiel_field');
          const documentSelect = document.getElementById('document_id_select');
          const materielSelect = document.getElementById('materiel_id_select');

          itemTypeIdSelect.addEventListener('change', function() {
            const selectedType = itemTypeIdSelect.value;

            if (selectedType === 'Document') {
              documentField.style.display = 'block';
              materielField.style.display = 'none';
              // Assurez-vous que l'ID du matériel est réinitialisé
              materielSelect.value = '';
            } else if (selectedType === 'Materiel') {
              documentField.style.display = 'none';
              materielField.style.display = 'block';
              // Assurez-vous que l'ID du document est réinitialisé
              documentSelect.value = '';
            } else {
              documentField.style.display = 'none';
              materielField.style.display = 'none';
            }
          });
        });
      </script>
    <% end %>
  </div>
</div>

bib/app/views/emprunts/_materiel_fields.html.erb
<div class="field">
  <%= form.label :materiel_id %>
  <%= form.collection_select :materiel_id, Materiel.all, :id, :marque %>
</div>

bib/app/views/emprunts/create.html.erb
<h1>Emprunts#create</h1>
<p>Find me in app/views/emprunts/create.html.erb</p>

bib/app/views/emprunts/destroy.html.erb
<h1>Emprunts#destroy</h1>
<p>Find me in app/views/emprunts/destroy.html.erb</p>

bib/app/views/emprunts/edit.html.erb
<div class="text-center">
<h1>Modifier l'emprunt</h1>

<%= render 'form' %>

</div>

bib/app/views/emprunts/index.html.erb
<div class="container text-center">
  <h1>Liste des emprunts</h1>

  <table class="table table-striped mx-auto">
    <thead>
      <tr>
        <th>Adhérent</th>
        <th>Item</th>
        <th>Type d'item</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
  <% @emprunts.each do |emprunt| %>
    <tr data-adherent="<%= emprunt.adherent.cin %>" data-item="<%= emprunt.item ? (emprunt.item_type == 'Document' ? emprunt.item.titre : emprunt.item.marque) : 'Aucun item associé' %>" data-item-type="<%= emprunt.item_type %>">
      <td><%= emprunt.adherent.cin %></td>
      <td>
        <% if emprunt.item %>
            <% if emprunt.item_type == "Document" %>
              <%= emprunt.item.titre %>
            <% elsif emprunt.item_type == "Materiel" %>
              <%= emprunt.item.marque %>
            <% end %>
            <% else %>
            <%= "Aucun item associé" %>
          <% end %>
      </td>
      <td><%= emprunt.item_type %></td>
      <td>
        <%= link_to 'Afficher', emprunt_path(emprunt), class: 'btn btn-primary btn-sm' %>
        <%= link_to 'Modifier', edit_emprunt_path(emprunt), class: 'btn btn-warning btn-sm' %>
        <%= link_to 'Supprimer', emprunt, method: :delete, data: { confirm: 'Êtes-vous sûr de vouloir supprimer cet emprunt ?' }, class: 'btn btn-danger btn-sm' %>
      </td>
    </tr>
  <% end %>
</tbody>

  </table>

  <%= link_to 'Nouvel emprunt', new_emprunt_path, class: 'btn btn-success d-block mx-auto' %>
  <button id="exportBtn" style="margin-left: 5px;" class="btn btn-primary">Export</button>
</div>

<script>
  document.getElementById("exportBtn").addEventListener("click", function() {
    // Créez un tableau pour stocker les données CSV
    let csvData = [];
    
    // Ajoutez l'en-tête CSV
    csvData.push(["adherent", "item", "item type"]);
    
    // Parcourez chaque ligne du tableau pour obtenir les informations
    document.querySelectorAll("tbody tr").forEach(function(row) {
      let adherent = row.getAttribute("data-adherent");
      let item = row.getAttribute("data-item");
      let itemType = row.getAttribute("data-item-type");
      csvData.push([adherent, item, itemType]);
    });

    // Convertissez le tableau en chaîne CSV
    let csvContent = "data:text/csv;charset=utf-8," + csvData.map(row => row.join(",")).join("\n");

    // Créez un élément d'ancrage pour télécharger le fichier CSV
    let encodedUri = encodeURI(csvContent);
    let link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", "emprunts.csv");
    document.body.appendChild(link);

    // Cliquez sur le lien pour télécharger le fichier CSV
    link.click();
  });
</script>

bib/app/views/emprunts/new.html.erb
<div class="text-center">
<h1>Nouvel emprunt</h1>

<%= render 'form' %>
</div>

bib/app/views/emprunts/show.html.erb
<div class="container">
  <div class="text-center">
    <h1>Détails de l'emprunt</h1>
  </div>

  <form>
    <div class="form-group row">
      <label for="adherent" class="col-sm-2 col-form-label">Adhérent :</label>
      <div class="col-sm-10">
        <input type="text" id="adherent" value="<%= @emprunt.adherent.nom %>" class="form-control" disabled>
      </div>
    </div>

    <div class="form-group row">
      <label for="item" class="col-sm-2 col-form-label">Item :</label>
      <div class="col-sm-10">
        <input type="text" id="item" value="<%= @emprunt.item_type == 'Document' ? @emprunt.item.titre : @emprunt.item.marque %>" class="form-control" disabled>
      </div>
    </div>

    <div class="form-group row">
      <label for="item_type" class="col-sm-2 col-form-label">Type d'item :</label>
      <div class="col-sm-10">
        <input type="text" id="item_type" value="<%= @emprunt.item_type %>" class="form-control" disabled>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-10 offset-sm-2">
        <%= link_to 'Modifier', edit_emprunt_path(@emprunt), class: 'btn btn-primary' %> |
        <%= link_to 'Retour', emprunts_path, class: 'btn btn-secondary' %>
      </div>
    </div>
  </form>
</div>

bib/app/views/emprunts/update.html.erb
<h1>Emprunts#update</h1>
<p>Find me in app/views/emprunts/update.html.erb</p>