bib/config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  #delete 'logout', to: 'sessions#destroy', as: 'logout'
  delete '/logout', to: 'sessions#destroy'




  # Routes pour Adhérents
  resources :adherents

  # Routes pour Documents
  resources :documents

  # Routes pour Matériels
  resources :materiels

  # Routes pour Emprunts
  resources :emprunts

  # Si vous avez une page d'accueil ou un contrôleur spécifique pour gérer la racine de l'application
  root 'home#index'  # Assurez-vous d'avoir un HomeController avec une action index
end

bib/app/views/layouts/_header.html.erb
<style>
    .navbar-nav.navbar-center {
        position: absolute;
        left: 50%;
        transform: translatex(-50%);
    }
</style>

<!-- Votre vue -->
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "BIBLIO ENSAK", root_path, class: "navbar-brand", id: "logo" %>

        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <% if logged_in? %>
                <ul class="nav navbar-nav navbar-center">
                    <li><%= link_to "Adhérent", adherents_path %></li>
                    <li><%= link_to "Document", documents_path %></li>
                    <li><%= link_to "Materiel", materiels_path %></li>
                    <li><%= link_to "Emprunt", emprunts_path %></li>
                </ul>
                <%= link_to "Déconnexion", logout_path, method: :delete, class: "btn btn-danger navbar-btn navbar-right" %>
            <% else %>
                <%= link_to "Connexion", login_path, class: "btn btn-success navbar-btn navbar-right" %>
            <% end %>
        </div>
    </div>
</nav>

bib/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Votre Application</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
  <!-- Bootstrap CSS via CDN -->
  <link rel="stylesheet" type="text/css" href="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!-- jQuery et Bootstrap JS via CDN -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  <script src="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <%= javascript_importmap_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <%= yield %>
</body>
</html>