bib/config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  #delete 'logout', to: 'sessions#destroy', as: 'logout'
  delete '/logout', to: 'sessions#destroy'




  # Routes pour Adhérents
  resources :adherents

  # Routes pour Documents
  resources :documents

  # Routes pour Matériels
  resources :materiels

  # Routes pour Emprunts
  resources :emprunts

  # Si vous avez une page d'accueil ou un contrôleur spécifique pour gérer la racine de l'application
  root 'home#index'  # Assurez-vous d'avoir un HomeController avec une action index
end

bib/app/models/materiel.rb
# app/models/materiel.rb
class Materiel < ApplicationRecord
  # Assume that Materiel can be of different types, handled via Single Table Inheritance (STI)
  self.inheritance_column = :Ttype

  # Validations
  validates :materiel_id, uniqueness: true, presence: true
  validates :marque, presence: true
  validates :type, presence: true
  validates :disponible, inclusion: { in: [true, false] }

  def display_name
    "#{materiel_id}-#{marque}"
  end

  # Vous pouvez ajouter des méthodes personnalisées ici pour gérer la logique spécifique au matériel
end

bib/app/controllers/materiels_controller.rb
class MaterielsController < ApplicationController
  before_action :authenticate_admin

  before_action :set_materiel, only: [:show, :edit, :update, :destroy]
  def authenticate_admin
    unless current_admin
      redirect_to login_path, alert: "Please sign in first."
    end
  end

  def index
    @materiels = Materiel.all
  end

  def show
  end

  def new
    @materiel = Materiel.new
  end


  def display_name
    "#{materiel_id}-#{marque}"
  end


  def edit
  end

  def create
    @materiel = Materiel.new(materiel_params)
    if @materiel.save
      redirect_to @materiel, notice: 'Materiel was successfully created.'
    else
      render :new
    end
  end

  def update
    if @materiel.update(materiel_params)
      redirect_to @materiel, notice: 'Materiel was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @materiel.destroy
    redirect_to materiels_url, notice: 'Materiel was successfully destroyed.'
  end

  private
    def set_materiel
      @materiel = Materiel.find(params[:id])
    end

    def materiel_params
      params.require(:materiel).permit(:materiel_id,:type,:marque, :disponible)
    end
end

bib/app/helpers/materiels_helper.rb
module MaterielsHelper
end

bib/app/views/materiels/_form.html.erb
<div class="container text-center">
  <%= form_with(model: @materiel) do |form| %>
    <% if @materiel.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@materiel.errors.count, "erreur") %> empêche(nt) la sauvegarde de ce matériel :</h2>
        <ul>
          <% @materiel.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group row">
      <%= form.label :materiel_id, class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= form.text_field :materiel_id, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <%= form.label :type, class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
            <%= form.select :type, options_for_select(["Autre", "PC"], selected: @materiel.type), {}, class: "form-control" %>

      </div>
    </div>

    <div class="form-group row">
      <%= form.label :marque, class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= form.text_field :marque, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <%= form.label :disponible, class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= form.check_box :disponible, class: "form-check-input" %>
        <%= form.label :disponible, class: "form-check-label" %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-10 offset-sm-2">
        <%= form.submit 'Enregistrer', class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

bib/app/views/materiels/create.html.erb
<h1>Materiels#create</h1>
<p>Find me in app/views/materiels/create.html.erb</p>

bib/app/views/materiels/destroy.html.erb
<h1>Materiels#destroy</h1>
<p>Find me in app/views/materiels/destroy.html.erb</p>

bib/app/views/materiels/edit.html.erb
<div class="container text-center">
<h1>Modifier le matériel</h1>

<%= render 'form' %>
</div>

bib/app/views/materiels/index.html.erb
<div class="container text-center">
  <h1>Liste des matériels</h1>

  <table class="table table-striped mx-auto">
    <thead>
      <tr>
        <th>ID</th>
        <th>Type</th>
        <th>Marque</th>
        <th>Disponible</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @materiels.each do |materiel| %>
        <tr>
          <td><%= materiel.materiel_id %></td>
          <td><%= materiel.type %></td>
          <td><%= materiel.marque %></td>
          <td><%= materiel.disponible ? 'Oui' : 'Non' %></td>
          <td>
            <%= link_to 'Afficher', materiel, class: 'btn btn-primary btn-sm' %>
            <%= link_to 'Modifier', edit_materiel_path(materiel), class: 'btn btn-warning btn-sm' %>
            <%= link_to 'Supprimer', materiel, method: :delete, data: { confirm: 'Êtes-vous sûr de vouloir supprimer ce matériel ?' }, class: 'btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'Ajouter un nouveau matériel', new_materiel_path, class: 'btn btn-success d-block mx-auto' %>
  <button id="exportBtn" style="margin-left: 5px;" class="btn btn-primary">Export</button>
</div>

<script>
  document.getElementById("exportBtn").addEventListener("click", function() {
    // Créez un tableau pour stocker les données CSV
    let csvData = [];
    
    // Ajoutez len-tête CSV
    csvData.push(["ID Matériel", "Marque", "Type","disponible"]);

    // Parcourez chaque adhérent pour obtenir ses informations
    <% @materiels.each do |materiel| %>
      csvData.push(["<%= materiel.materiel_id %>", "<%= materiel.marque %>", "<%= materiel.type %>", "<%= materiel.disponible %>"]);
    <% end %>

    // Convertissez le tableau en chaîne CSV
    let csvContent = "data:text/csv;charset=utf-8," + csvData.map(row => row.join(",")).join("\n");

    // Créez un élément d'ancrage pour télécharger le fichier CSV
    let encodedUri = encodeURI(csvContent);
    let link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", "materiels.csv");
    document.body.appendChild(link);

    // Cliquez sur le lien pour télécharger le fichier CSV
    link.click();
  });
</script>

bib/app/views/materiels/new.html.erb
<div class="container text-center">
  <h1>Nouveau matériel</h1>
  <%= render 'form' %>
</div>

bib/app/views/materiels/show.html.erb
<div class="container text-center">
  <div>
    <p>
      <strong>Type :</strong>
      <%= text_field_tag 'type', @materiel.type, readonly: true, class: 'form-control', disabled: true %>
    </p>

    <p>
      <strong>Marque :</strong>
      <%= text_field_tag 'marque', @materiel.marque, readonly: true, class: 'form-control', disabled: true %>
    </p>

    <p>
      <strong>Disponible :</strong>
      <%= text_field_tag 'disponible', @materiel.disponible ? 'Oui' : 'Non', readonly: true, class: 'form-control', disabled: true %>
    </p>

    <%= link_to 'Modifier', edit_materiel_path(@materiel), class: 'btn btn-primary' %> |
    <%= link_to 'Retour', materiels_path, class: 'btn btn-secondary' %>
  </div>
</div>

bib/app/views/materiels/update.html.erb
<h1>Materiels#update</h1>
<p>Find me in app/views/materiels/update.html.erb</p>