bib/config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  #delete 'logout', to: 'sessions#destroy', as: 'logout'
  delete '/logout', to: 'sessions#destroy'




  # Routes pour Adhérents
  resources :adherents

  # Routes pour Documents
  resources :documents

  # Routes pour Matériels
  resources :materiels

  # Routes pour Emprunts
  resources :emprunts

  # Si vous avez une page d'accueil ou un contrôleur spécifique pour gérer la racine de l'application
  root 'home#index'  # Assurez-vous d'avoir un HomeController avec une action index
end

bib/app/models/document.rb
# app/models/document.rb
class Document < ApplicationRecord
  # Validations
  self.inheritance_column = :document_type

  validates :type, presence: true
  validates :titre, presence: true
  validates :isbn, uniqueness: true, presence: true
  validates :disponible, inclusion: { in: [true, false] }
  validates :auteur, presence: true  # Assuming you want it to be required, adjust as needed

  def display_name
    "#{isbn}-#{titre} by #{auteur}"  # Optionally include the author in the display name
  end
end

bib/app/controllers/documents_controller.rb
# app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :authenticate_admin

  before_action :set_document, only: [:show, :edit, :update, :destroy]
  def authenticate_admin
    unless current_admin
      redirect_to login_path, alert: "Please sign in first."
    end
  end

  def index
    @documents = Document.all
  end

  def show
  end

  def new
    @document = Document.new
  end

  def edit
  end

  def create
    @document = Document.new(document_params)
    if @document.save
      redirect_to @document, notice: 'Document was successfully created.'
    else
      render :new
    end
  end

  def update
    if @document.update(document_params)
      redirect_to @document, notice: 'Document was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @document.destroy
    redirect_to documents_url, notice: 'Document was successfully destroyed.'
  end

  private
    def set_document
      @document = Document.find(params[:id])
    end

    def document_params
      params.require(:document).permit(:type, :titre, :isbn, :disponible, :auteur)
    end
end

bib/app/helpers/documents_helper.rb
module DocumentsHelper
end

bib/app/views/documents/_form.html.erb
<div class="container">
  <div class="text-center">
    <%= form_with(model: @document) do |form| %>
      <% if @document.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@document.errors.count, "erreur") %> empêche(nt) la sauvegarde de ce document :</h2>
          <ul>
            <% @document.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group row">
        <%= form.label :type, class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10">
            <%= form.select :type, ['Livres', 'Revues', 'Dictionnaires', 'BD'], { include_blank: 'Sélectionner un type' }, class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label :titre, class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10">
          <%= form.text_field :titre, class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label :isbn, class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10">
          <%= form.text_field :isbn, class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label :auteur, class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10">
          <%= form.text_field :auteur, class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label :disponible, class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10">
          <%= form.check_box :disponible, class: "form-check-input" %>
          <%= form.label :disponible, class: "form-check-label" %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-sm-10 offset-sm-2">
          <%= form.submit 'Enregistrer', class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

bib/app/views/documents/create.html.erb
<h1>Documents#create</h1>
<p>Find me in app/views/documents/create.html.erb</p>

bib/app/views/documents/destroy.html.erb
<h1>Documents#destroy</h1>
<p>Find me in app/views/documents/destroy.html.erb</p>

bib/app/views/documents/edit.html.erb
<div class="container">
  <div class="text-center">
    <h1>Modifier le document</h1>
  </div>

  <%= render 'form', document: @document %>
</div>

bib/app/views/documents/index.html.erb
<div class="container text-center">
  <h1>Liste des documents</h1>

  <table class="table table-striped mx-auto">
    <thead>
      <tr>
        <th>Type</th>
        <th>Titre</th>
        <th>Auteur</th> <!-- Added column for author -->
        <th>Disponible</th>
        <th>ISBN</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @documents.each do |document| %>
        <tr>
          <td><%= document.type %></td>
          <td><%= document.titre %></td>
          <td><%= document.auteur %></td> <!-- Displaying author -->
          <td><%= document.disponible ? 'Oui' : 'Non' %></td>
          <td><%= document.isbn %></td>
          <td>
            <%= link_to 'Voir', document, class: 'btn btn-primary btn-sm' %>
            <%= link_to 'Modifier', edit_document_path(document), class: 'btn btn-warning btn-sm' %>
            <%= link_to 'Supprimer', document, method: :delete, data: { confirm: 'Êtes-vous sûr de vouloir supprimer ce document ?' }, class: 'btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'Ajouter un nouveau document', new_document_path, class: 'btn btn-success d-block mx-auto' %>
  <button id="exportBtn" style="margin-left: 5px;" class="btn btn-primary">Export</button>
</div>

<script>
  document.getElementById("exportBtn").addEventListener("click", function() {
    // Créez un tableau pour stocker les données CSV
    let csvData = [];
    
    // Ajoutez len-tête CSV
    csvData.push(["Type", "Titre", "Auteur","Disponible","ISBN"]);

    // Parcourez chaque adhérent pour obtenir ses informations
    <% @documents.each do |document| %>
      csvData.push(["<%= document.type %>", "<%= document.titre %>", "<%= document.auteur %>", "<%= document.disponible %>", "<%= document.isbn %>"]);
    <% end %>

    // Convertissez le tableau en chaîne CSV
    let csvContent = "data:text/csv;charset=utf-8," + csvData.map(row => row.join(",")).join("\n");

    // Créez un élément d'ancrage pour télécharger le fichier CSV
    let encodedUri = encodeURI(csvContent);
    let link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", "doc.csv");
    document.body.appendChild(link);

    // Cliquez sur le lien pour télécharger le fichier CSV
    link.click();
  });
</script>

bib/app/views/documents/new.html.erb
<!-- app/views/materiels/new.html.erb -->
<div class="container">
  <div class="text-center mb-3">
    <h1>Nouveau document</h1>
  </div>

  <%= render 'form', materiel: @materiel %>

  
</div>

bib/app/views/documents/show.html.erb
<div class="container">
  <div class="text-center">
    <h1>Détails du document</h1>
  </div>

  <div class="form-horizontal">
    <div class="form-group row">
      <label for="type" class="col-sm-2 col-form-label">Type :</label>
      <div class="col-sm-10">
        <input type="text" id="type" value="<%= @document.type %>" readonly class="form-control" disabled>
      </div>
    </div>

    <div class="form-group row">
      <label for="titre" class="col-sm-2 col-form-label">Titre :</label>
      <div class="col-sm-10">
        <input type="text" id="titre" value="<%= @document.titre %>" readonly class="form-control" disabled>
      </div>
    </div>

    <div class="form-group row">
      <label for="auteur" class="col-sm-2 col-form-label">Auteur :</label>
      <div class="col-sm-10">
        <input type="text" id="auteur" value="<%= @document.auteur %>" readonly class="form-control" disabled>
      </div>
    </div>

    <div class="form-group row">
      <label for="disponible" class="col-sm-2 col-form-label">Disponible :</label>
      <div class="col-sm-10">
        <input type="text" id="disponible" value="<%= @document.disponible ? 'Oui' : 'Non' %>" readonly class="form-control" disabled>
      </div>
    </div>

    <div class="form-group row">
      <label for="isbn" class="col-sm-2 col-form-label">ISBN :</label>
      <div class="col-sm-10">
        <input type="text" id="isbn" value="<%= @document.isbn %>" readonly class="form-control" disabled>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-10 offset-sm-2">
        <%= link_to 'Modifier', edit_document_path(@document), class: 'btn btn-primary' %> |
        <%= link_to 'Retour à la liste', documents_path, class: 'btn btn-secondary' %>
      </div>
    </div>
  </div>
</div>

bib/app/views/documents/update.html.erb
<h1>Documents#update</h1>
<p>Find me in app/views/documents/update.html.erb</p>